### PR TITLE
add docker labels to each logentry

### PR DESCRIPTION
**Pull request by jeffreykoetsier**
Add Docker Labels to each log entry.

* Switch available to enable adding of labels to log entry
* Option to define a regex to select specific labels
* Put label key/value pairs underneath a single key or in the root of the log object

### CODE REVIEW

**Review by cammellos — APPROVED** [review]
Looks good to me, thanks for the useful contribution!

**Comment by mcollina** [comment]
@cammellos what's your npm handle? I'll add you there as well and you can do a release.

**Comment by cammellos** [comment]
@mcollina thanks, it's cammellos, I have just registered

**Comment by mcollina** [comment]
done. Bump the minor for this one.

Il giorno lun 1 ott 2018 alle ore 12:27 Andrea Maria Piana <
notifications@github.com> ha scritto:

**Comment by cammellos** [comment]
@jeffreykoetsier published on 1.6.4, thanks for the contribution!

**Pull request merged**
